Fix locale dependence on fallback from_chars implementation
boostorg/charconv pull request #123
Opened 2024-01-18 08:42 UTC by mborland

Closes: #122

2024-01-18 12:05 UTC, Flamefire requested changes

2024-01-18 12:05 UTC, Flamefire commented on include/boost/charconv/detail/from_chars_float_impl.hpp
> +    BOOST_CHARCONV_USE_LOCALE(c_locale);
The locale is never reset so this changes the users locale, doesn't it? I'd suggest to use an RAII class instead such that the reset cannot be forgotten. Also not sure what happens if you call `freelocale` on a locale that is in use (i.e. after setlocale/uselocale), I guess that is UB/use-after-free

Using an RAII object has the additional advantage of resulting in less changes as you can keep the "return"s

2024-01-19 07:18 UTC, mborland commented on include/boost/charconv/detail/from_chars_float_impl.hpp
> +    BOOST_CHARCONV_USE_LOCALE(c_locale);
If I modify to `const auto prev_locale = BOOST_CHARCONV_USE_LOCALE(c_locale);` the [man pages](https://man7.org/linux/man-pages/man3/uselocale.3.html) say it is to return the current locale. Calling `BOOST_CHARCONV_USE_LOCALE(prev_locale)` before freeing the newly allocated locale causes the test to fail as if none of this PR was present. Any insight on to why that may be?

2024-01-19 08:42 UTC, mborland commented on include/boost/charconv/detail/from_chars_float_impl.hpp
> +    BOOST_CHARCONV_USE_LOCALE(c_locale);
The answer is the conversions were incorrect but matched because the C locale was never reverted back. Added a known validation value to the tests.

2024-01-22 09:34 UTC, merged